#!/usr/bin/env sh

limelight -m config width            1
limelight -m config radius           0
limelight -m config placement        interior
limelight -m config active_color     0xFF2EDD5A 
limelight -m config normal_color     0x00FFFFFF

echo "limelight configuration loaded.."
