# mongo and redis containers
version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - "27018:27017"

  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6380:6379"
