local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', function()
    builtin.find_files({ hidden = true })
end)
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > "), hidden = true })
end)
vim.keymap.set("n", "<leader>psw", function()
    builtin.grep_string({ search = vim.fn.expand("<cword>"), hidden = true })
end, {})
vim.keymap.set("n", "<leader>psW", function()
    builtin.grep_string({ search = vim.fn.expand("<cWORD>"), hidden = true })
end, {})
